server:
  port: 8082

integration:
  url: your_url_address
  trust-store-path: C:\Users\admin\Desktop\call-external-service\keystore\truststore
  trust-store-password: changeit
  key-store-path: C:\Users\admin\Desktop\call-external-service\keystore\point_5378.p12
  key-store-password: your_password
  key-password: your_password

credentials:
  point: 5378



